Repository rhel-lightspeed/command-line-assistant, pull requests merged in 2025-08, with the labels that each got.

#453 [RSPEED-1796] Fix typo in warning message for total input size
  command_line_assistant/commands/chat.py
Labels: kind/bug-fix

#450 Change pre-commit autoupdate schedule to monthly
  .pre-commit-config.yaml
Labels: skip/changelog, kind/misc

#470 Update dependencies every month
  renovate.json
Labels: skip/changelog, kind/misc, tests/skip

#441 [RSPEED-1762] Catch OSError being thrown by submit method
  command_line_assistant/daemon/http/query.py
  tests/daemon/http/test_query.py
Labels: kind/bug-fix

#380 [RSPEED-1715, RSPEED-825] Refactor commands module
  command_line_assistant/client.py
  command_line_assistant/commands/__init__.py
  command_line_assistant/commands/base.py
  command_line_assistant/commands/chat.py
  command_line_assistant/commands/cli.py
  command_line_assistant/commands/feedback.py
  command_line_assistant/commands/history.py
  command_line_assistant/commands/shell.py
  command_line_assistant/dbus/client.py
  command_line_assistant/dbus/interfaces/history.py
  command_line_assistant/history/manager.py
  command_line_assistant/rendering/renderers.py
  command_line_assistant/rendering/renders/interactive.py
  command_line_assistant/utils/cli.py
  docs/source/commands/cli.rst
  docs/source/commands/index.rst
  docs/source/dbus/client.rst
  docs/source/dbus/index.rst
  docs/source/rendering/index.rst
  docs/source/rendering/renderers.rst
  tests/commands/test_chat.py
  tests/commands/test_cli.py
  tests/commands/test_feedback.py
  tests/commands/test_history.py
  tests/commands/test_shell.py
  tests/conftest.py
  tests/dbus/interfaces/test_history.py
  tests/dbus/test_client.py
  tests/history/test_manager.py
  tests/rendering/test_renderers.py
  tests/test_client.py
  uv.lock
Labels: kind/refactor

#475 Pin dasbus to 1.4 and pygobject to 3.40.1
  pyproject.toml
  uv.lock
Labels: kind/misc, dependencies

#477 Fix container builds in Konflux
  container-images/default.Containerfile
  pyproject.toml
Labels: skip/changelog, kind/misc

#478 Add multi-arch builds in Konflux
  .tekton/pipeline-build.yaml
  .tekton/pull_request.yaml
  .tekton/push.yaml
  container-images/default.Containerfile
Labels: skip/changelog, kind/misc
