Repository rhel-lightspeed/command-line-assistant, pull requests merged in 2025-07, with the labels that each got.

#407 [RSPEED-1626] Add missing line for %files in rpmbuild
  packaging/command-line-assistant.spec
Labels: kind/bug-fix

#409 Organize optional dependencies
  .readthedocs.yaml
  Makefile
  poetry.lock
  pyproject.toml
Labels: skip/changelog, kind/misc

#402 [RSPEED-1549, RSPEED-1716] Remove and deprecate verify_ssl option
  command_line_assistant/config/schemas/backend.py
  command_line_assistant/daemon/http/session.py
  data/development/xdg/command-line-assistant/config.toml
  data/release/xdg/config.toml
  tests/config/schemas/test_backend.py
  tests/config/schemas/test_schema.py
  tests/config/test_config.py
  tests/conftest.py
  tests/daemon/http/test_query.py
  tests/daemon/http/test_session.py
Labels: skip/changelog, kind/refactor

#401 [RSPEED-1549] Cleanup from sonarqube alerts
  command_line_assistant/commands/chat.py
  command_line_assistant/daemon/database/manager.py
  command_line_assistant/daemon/http/adapters.py
  command_line_assistant/daemon/http/query.py
  command_line_assistant/utils/files.py
Labels: skip/changelog, kind/refactor

#405 [RSPEED-1065, RSPEED-1626] Add Containerfile for CLA
  Containerfile
  Makefile
  container-images/default.Containerfile
  scripts/prepare_release.py
Labels: kind/enhancement

#419 renovate: Enable best practices config
  renovate.json
Labels: skip/changelog, kind/misc

#423 [RSPEED-1564] Add horizontal line after spinner message
  command_line_assistant/commands/chat.py
Labels: kind/bug-fix

#424 Fix regression for `c history`
  command_line_assistant/client.py
  command_line_assistant/utils/cli.py
  tests/test_client.py
Labels: kind/bug-fix

#425 Prepare for release v0.4.1
  Makefile
  command_line_assistant/constants.py
  container-images/default.Containerfile
  data/release/man/c.1
  data/release/man/clad.8
  data/release/selinux/clad.te
  docs/source/conf.py
  packaging/command-line-assistant.spec
  pyproject.toml
  tests/dbus/interfaces/test_chat.py
Labels: skip/changelog, kind/misc

#426 [RSPEED-1771] Setup Konflux builds
  .tekton/pipeline-build.yaml
  .tekton/pull_request.yaml
  .tekton/push.yaml
  container-images/default.Containerfile
Labels: kind/misc

#436 Change version update policy
  poetry.lock
  pyproject.toml
  renovate.json
  tests/daemon/database/repository/test_base.py
Labels: skip/changelog, kind/dependencies
