Repository rhel-lightspeed/command-line-assistant, pull requests merged in 2025-06, with the labels that each got.

#378 Update .packit.yaml target distros
  .packit.yaml
Labels: skip/changelog, kind/misc

#377 [RSPEED-1564] Add horizontal lines back
  command_line_assistant/commands/chat.py
Labels: kind/bug-fix

#353 [RSPEED-1073] Limit permission for history database to own user
  command_line_assistant/daemon/database/manager.py
  tests/config/schemas/test_database.py
Labels: kind/bug-fix

#396 RSPEED-1626: packaging: Add tmpfiles.d config for /var folder
  data/release/systemd/clad.tmpfiles.conf
  packaging/command-line-assistant.spec
Labels: kind/enhancement
