Repository rhel-lightspeed/command-line-assistant, pull requests merged in 2025-04, with the labels that each got.

#312 [RSPEED-817] Add label automation to help in release changelog
  .github/release.yml
  .github/workflows/enforce_labels.yml
  .github/workflows/jira-links.yml
Labels: skip/changelog, kind/feature

#311 [RSPEED-568] Add tmpfs SELinux domain
  data/release/selinux/clad.te
Labels: kind/security

#306 [RSPEED-829] Add check in clear(-all) to check if there is any chat to clean
  command_line_assistant/commands/history.py
  command_line_assistant/dbus/interfaces/chat.py
  tests/commands/test_history.py
  tests/dbus/interfaces/test_chat.py
Labels: kind/bug-fix

#313 Remove redundant exception message
  command_line_assistant/rendering/renders/interactive.py
  tests/rendering/renders/test_interactive.py
Labels: skip/changelog, kind/feature

#315 Remove outdated sections from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip/changelog, kind/misc

#314 Remove config.toml from root folder
  config.toml
  data/development/certificate/fake-certificate.pem
  data/development/certificate/fake-key.pem
  data/development/xdg/command-line-assistant/config.toml
Labels: skip/changelog, kind/misc

#319 [RSPEED-925] Update colors in MarkdownRenderer to make the text more visible
  command_line_assistant/rendering/renders/markdown.py
  tests/rendering/renders/test_markdown.py
Labels: kind/bug-fix

#324 Disable colors in output
  command_line_assistant/initialize.py
Labels: kind/enhancement

#327 Revert "Disable colors in output"
  command_line_assistant/initialize.py
Labels: skip/changelog, kind/bug-fix

#318 Add labels for renovate pull requests
  renovate.json
Labels: skip/changelog, kind/misc

#320 [RSPEED-844] Apply fixes to commands description and manpage in general
  command_line_assistant/commands/chat.py
  command_line_assistant/commands/feedback.py
  command_line_assistant/commands/history.py
  command_line_assistant/commands/shell.py
  command_line_assistant/utils/cli.py
  data/release/man/c.1
  data/release/man/clad.8
  docs/source/man/clad.8.rst
Labels: kind/bug-fix

#321 [RSPEED-823] Fix legal message not showing up on each session
  command_line_assistant/utils/files.py
Labels: kind/bug-fix

#331 Add missing property and config to launch.json
  .vscode/launch.json
Labels: skip/changelog, kind/bug-fix

#269 Create the history.db parent directory
  command_line_assistant/daemon/database/manager.py
Labels: kind/enhancement

#333 [RSPEED-898] Generate tarball on every tag release
  .github/workflows/release.yml
  Makefile
  packaging/command-line-assistant.spec
Labels: skip/changelog, kind/enhancement

#332 Use mypy instead of pyright
  .github/workflows/sanity.yml
  .pre-commit-config.yaml
  command_line_assistant/config/__init__.py
  command_line_assistant/daemon/database/models/base.py
  command_line_assistant/daemon/database/models/chat.py
  command_line_assistant/daemon/database/models/history.py
  command_line_assistant/daemon/database/repository/chat.py
  command_line_assistant/daemon/database/repository/history.py
  command_line_assistant/dbus/structures/base.py
  command_line_assistant/history/plugins/local.py
  command_line_assistant/logger.py
  command_line_assistant/terminal/parser.py
  command_line_assistant/utils/environment.py
  setup.py
  tests/config/test_config.py
Labels: skip/changelog, kind/misc

#337 Include both ~/.config and data/development config
  .vscode/launch.json
  command_line_assistant/utils/environment.py
Labels: skip/changelog, kind/bug-fix

#338 Revert type annotations for SQLAlchemy
  command_line_assistant/daemon/database/models/base.py
  command_line_assistant/daemon/database/models/chat.py
  command_line_assistant/daemon/database/models/history.py
Labels: skip/changelog, kind/bug-fix

#336 Point the test job to the `develop` branch
  .packit.yaml
Labels: skip/changelog, kind/tests

#330 [RSPEED-770] Add general file locking mechanism
  command_line_assistant/commands/chat.py
  command_line_assistant/commands/shell.py
  command_line_assistant/utils/files.py
  tests/commands/test_chat.py
  tests/commands/test_shell.py
  tests/conftest.py
  tests/utils/test_files.py
Labels: kind/enhancement

#305 [RSPEED-781] Fix chat description and name defaults
  command_line_assistant/commands/chat.py
  tests/commands/test_chat.py
Labels: kind/bug-fix

#340 Add fedora42 builds in COPR
  .packit.yaml
  data/release/selinux/clad.fc
  data/release/systemd/clad.service
  packaging/command-line-assistant.spec
Labels: skip/changelog, kind/misc

#347 [RSPEED-1118] Default to --all in history command
  command_line_assistant/commands/history.py
  tests/commands/test_history.py
Labels: kind/bug-fix

#342 [RSPEED-991] Submit systeminfo to backend as part of context
  command_line_assistant/commands/chat.py
  command_line_assistant/dbus/interfaces/chat.py
  command_line_assistant/dbus/structures/chat.py
  tests/dbus/interfaces/test_chat.py
Labels: kind/enhancement

#351 [RSPEED-1150] Fix unprocessable entity request for inference
  command_line_assistant/dbus/interfaces/chat.py
  tests/dbus/interfaces/test_chat.py
Labels: kind/bug-fix
