Repository rhel-lightspeed/command-line-assistant, pull requests merged in 2025-05, with the labels that each got.

#352 [RSPEED-952] Warn if .bashrc.d missing
  command_line_assistant/commands/shell.py
  tests/commands/test_shell.py
Labels: kind/bug-fix

#364 Honor the http_proxy environment variables
  command_line_assistant/config/schemas/backend.py
  tests/config/schemas/test_schema.py
Labels: kind/bug-fix

#297 [RSPEED-816] Add support for plain, simple output
  command_line_assistant/client.py
  command_line_assistant/commands/base.py
  command_line_assistant/commands/chat.py
  command_line_assistant/commands/feedback.py
  command_line_assistant/commands/history.py
  command_line_assistant/rendering/renders/markdown.py
  command_line_assistant/rendering/renders/spinner.py
  command_line_assistant/rendering/renders/text.py
  command_line_assistant/utils/cli.py
  command_line_assistant/utils/renderers.py
  data/release/man/c.1
  pyproject.toml
  tests/commands/test_chat.py
  tests/rendering/renders/test_markdown.py
  tests/rendering/renders/test_text.py
Labels: kind/feature

#366 Prepare for release v0.4.0
  Makefile
  command_line_assistant/constants.py
  data/release/man/c.1
  data/release/man/clad.8
  data/release/selinux/clad.te
  docs/source/conf.py
  packaging/command-line-assistant.spec
  pyproject.toml
Labels: skip/changelog, kind/misc

#349 Update prepare-release script to create a new branch
  scripts/prepare_release.py
Labels: skip/changelog, kind/misc
